Update  NodeJS Versions to 22 23 24

diff --git a/.github/workflows/build-and-push.yml b/.github/workflows/build-and-push.yml
--- a/.github/workflows/build-and-push.yml
+++ b/.github/workflows/build-and-push.yml
@@ -185,15 +185,67 @@ jobs:
         docker run --rm ${{ secrets.DOCKERHUB_REPO }}/java-${{ matrix.java_version }}:latest java -version 2>&1 \
         | grep "version" || echo "Java version test failed"
 
+
+  # Job 4: Build NodeJS Images
+  build-nodejs-images:
+    name: Build nodejs Images
+    needs: test-base-image
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        nodejs_version: [22, 23]
+
+    steps:
+    - name: Checkout Code
+      uses: actions/checkout@v3
+
+    - name: Log in to DockerHub
+      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
+
+    - name: Build nodejs Image
+      working-directory: ./nodejs-layer
+      run: |
+        docker buildx create --use
+        docker buildx build \
+          --platform linux/amd64,linux/arm64 \
+          --cache-from=type=registry,ref=${{ secrets.DOCKERHUB_REPO }}/java-${{ matrix.nodejs_version }}:cache \
+          --cache-to=type=registry,ref=${{ secrets.DOCKERHUB_REPO }}/java-${{ matrix.nodejs_version }}:cache,mode=max \
+          --build-arg BASE_IMAGE=${{ secrets.DOCKERHUB_REPO }}/base-image:latest \
+          --build-arg nodejs_VERSION=${{ matrix.nodejs_version }} \
+          -t ${{ secrets.DOCKERHUB_REPO }}/java-${{ matrix.nodejs_version }}:latest \
+          -t ${{ secrets.DOCKERHUB_REPO }}/java-${{ matrix.nodejs_version }}:v${{ matrix.nodejs_version }}-$(date +%Y%m%d)-${{ github.sha }} \
+          -t ${{ secrets.DOCKERHUB_REPO }}/java-${{ matrix.nodejs_version }}:cache \
+          --push .
+
+  test-nodejs-images:
+    name: Test nodejs Images
+    needs: build-nodejs-images
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        java_version: [22, 23]
+
+    steps:
+    - name: Log in to DockerHub
+      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
+
+    - name: Test Java Image
+      run: |
+        docker run --rm ${{ secrets.DOCKERHUB_REPO }}/java-${{ matrix.nodejs_version }}:latest nodejs -version 2>&1 \
+        | grep "version" || echo "nodejs version test failed"
+
+
+
   # Job 4: Run E2E Tests
   run-e2e-tests:
     name: Run E2E Tests
-    needs: [test-python-images, test-java-images]
+    needs: [test-python-images, test-java-images, test-nodejs-images]
     runs-on: ubuntu-latest
     strategy:
       matrix:
         python_version: [3.11, 3.12]
         java_version: [11, 17]
+        nodejs_version: [22, 23]
 
     steps:
     - name: Checkout Code
@@ -210,6 +262,7 @@ jobs:
         echo "DOCKERHUB_REPO=${{ secrets.DOCKERHUB_REPO }}"
         echo "PYTHON_VERSION=${{ matrix.python_version }}"
         echo "JAVA_VERSION=${{ matrix.java_version }}"
+        echo "nodejs_VERSION=${{ matrix.nodejs_version }}"
         cat ./tests/docker-compose.yml
 
     - name: Set up Docker Compose for E2E
@@ -219,6 +272,7 @@ jobs:
         DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}
         PYTHON_VERSION: ${{ matrix.python_version }}
         JAVA_VERSION: ${{ matrix.java_version }}
+        nodejs_VERSION: ${{ matrix.nodejs_version }}
 
     - name: Run E2E Tests
       run: |
@@ -233,6 +287,7 @@ jobs:
         DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}
         PYTHON_VERSION: ${{ matrix.python_version }}
         JAVA_VERSION: ${{ matrix.java_version }}
+        nodejs_VERSION: ${{ matrix.nodejs_version }}
 
     - name: Clean Up
       if: always()
@@ -246,6 +301,7 @@ jobs:
         DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}
         PYTHON_VERSION: ${{ matrix.python_version }}
         JAVA_VERSION: ${{ matrix.java_version }}
+        nodejs_VERSION: ${{ matrix.nodejs_version }}
 
 
 
